directory: ~/Music
library: ~/Music/library.blb
plugins: info scrub
import:
  move: yes
  write: yes
  timid: yes
path_format: $albumartist_-_$album%aunique{}/$track - $title
paths:
  default: $albumartist - $album%aunique{}/$track - $title
  singleton: Singletons/$artist - $title
color: yes
timid: yes
scrub:
  auto: no
clutter:
  - Thumbs.DB
  - Thumbs.db
  - .DS_Store
  - .directory
  - desktop.ini
  - Desktop.ini
match:
  preferred:
    countries: ['US|CA', 'GB|UK']
    media: ['CD', 'Digital Media|File']
    original_year: yes
replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\.$': _
  '\s+$': ''
  '\s': '_'
  '“': ''
  '”': ''
